# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e06cef5d10894fa64d0363ea9218acd63d9f7a8efddc0a6da97b81a185537e5bb52298d2abc339819cb04502ebb2a335b02d098c1754fcb05a5d389ab470065f

test:
  secret_key_base: f4bde4a4c9c82884b3df7a7c4a00126e28e38d3307beab0c26a136a09c0e6da1543fedaf057f248a3aa2dd49dfcbf0e9cc8806dfe8f1faa44b6845d6e80a7324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
